### ISSUE TITLE
Invalid Download

### ISSUE THREAD

**Issue by ivoneijr** [WindowsGSM/WindowsGSM#120] opened 2022-05-03 00:34 UTC
**Describe the bug**
invalid download link 

**To Reproduce**
1. Go to https://windowsgsm.com/download/
2. Click on 'download latest exe()' 
3. Redirected to not found page `https://github.com/WindowsGSM/WindowsGSM/releases/download//WindowsGSM.exe` 

**Expected behavior**
Valid download link

**Screenshots**
![image](https://user-images.githubusercontent.com/6401435/166354643-81a433f8-394b-43f7-9106-5c352bf295a4.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser any
 - Version any

**Comment by mrnoahfink** [comment] 2022-05-03 01:18
Try this link - https://github.com/WindowsGSM/WindowsGSM/releases/download/v1.23.0/WindowsGSM.exe

Seem you have extra / before Windows.exe

**Comment by BattlefieldDuck** [comment] 2022-05-03 15:47
thanks for the report @ivoneijr ! The issue is fixed now.

**Closed by BattlefieldDuck** 2022-05-03 15:47 UTC
